### ISSUE TITLE
gets killed by OOM killer despite low -mf and low predicted footprint

### ISSUE THREAD

**Issue by o-smirnov** [caracal-pipeline/crystalball#45]
Not sure where to start diagnosing this. Quite a few sources here, but the MS only has two scans:
```
(stimela) oms@baker:~/projects/ConjBoom/msdir$ crystalball -sm primary-catalog/fitted.PKS1934.UBand.wsclean.cat.txt -f 0 1625623568_sdp_l0-cal.ms
2021-07-08 14:25:38 | INFO     | crystalball:_predict | Crystalball version 0.3.0
2021-07-08 14:25:38 | INFO     | wsclean:import_from_wsclean | primary-catalog/fitted.PKS1934.UBand.wsclean.cat.txt contains 7779 components
2021-07-08 14:25:38 | INFO     | wsclean:import_from_wsclean | Total flux of 7779 selected components is 19.734272 Jy
Successful read/write open of default-locked table 1625623568_sdp_l0-cal.ms: 24 columns, 122610 rows
2021-07-08 14:25:39 | INFO     | budget:get_budget | --------------------------------------------------
2021-07-08 14:25:39 | INFO     | budget:get_budget | Budgeting
2021-07-08 14:25:39 | INFO     | budget:get_budget | --------------------------------------------------
2021-07-08 14:25:39 | INFO     | budget:get_budget | system RAM = 503.37 GB
2021-07-08 14:25:39 | INFO     | budget:get_budget | nr of logical CPUs = 128
2021-07-08 14:25:39 | INFO     | budget:get_budget | nr sources = 7779
2021-07-08 14:25:39 | INFO     | budget:get_budget | nr rows    = 122610
2021-07-08 14:25:39 | INFO     | budget:get_budget | nr chans   = 4096
2021-07-08 14:25:39 | INFO     | budget:get_budget | nr corrs   = 4
2021-07-08 14:25:39 | INFO     | budget:get_budget | sources per chunk = 25 (auto settings)
2021-07-08 14:25:39 | INFO     | budget:get_budget | rows per chunk    = 2577 (auto settings)
2021-07-08 14:25:39 | INFO     | budget:get_budget | expected memory usage = 50.33 GB
2021-07-08 14:25:39 | INFO     | crystalball:_predict | Field J1939-6342 DDID 0 rows 96990 chans 4096 corrs 4
[################################          ] | 77% Complete (Estimate) | 40m43s / ~52m14sKilled
(stimela) oms@baker:~/projects/ConjBoom/msdir$ 
```

**Comment by sjperkins** [comment]
I would hazard that crystalball fell afoul of the OOM Killer on Linux:

https://stackoverflow.com/questions/726690/what-killed-my-process-and-why

although it should reasonably be taking 50GB out of the 503GB total based on the budgeting above.

**Comment by sjperkins** [comment]
Does 

```bash
dmesg -T| grep -E -i -B100 'killed process'
```

or

```bash
sudo journalctl -xb
```

reveal anything interesting as per the SO answers above?

**Comment by o-smirnov** [comment]
Yep:
```
[Thu Jul  8 15:06:19 2021] Out of memory: Killed process 3132987 (crystalball) total-vm:1588823956kB, anon-rss:517128560kB, file-rss:480kB, shmem-rss:0kB, UID:1001 pgtables:3077244kB oom_score_adj:0
```

But anyway, I caught it in the act on a subsequent run, it's been using well over 500 GB of RAM. So over x10 the estimate. Which knob can I tweak to try to reduce this?

**Comment by paoloserra** [comment]
> Which knob can I tweak to try to reduce this?

probably the memory fraction

**Comment by sjperkins** [comment]
Hmmmm, thats unexpected, It felt like we had this pinned down pretty well. As, @paoloserra says, the memory fraction, but based on the Budgeting you posted above it shouldn't be asking for much (10% of system IIRC)

**Comment by o-smirnov** [comment]
I tried ``-mf 0.02``. Watched memory use grow steadily to 500+ GB, killed it. It's almost like a memory leak?
```
2021-07-08 15:57:33 | INFO     | budget:get_budget | sources per chunk = 5 (auto settings)
2021-07-08 15:57:33 | INFO     | budget:get_budget | rows per chunk    = 515 (auto settings)
```
Also, out of curiosity: that's 0.02 vs 0.1. But it seems to have reduced the chunk size by a factor of 5 in both the source and row dimension. Should that not decrease footprint by x25 then, in theory?

**Comment by sjperkins** [comment]
> 
> 
> I tried `-mf 0.02`. Watched memory use grow steadily to 500+ GB, killed it. It's almost like a memory leak?
> 
> ```
> 2021-07-08 15:57:33 | INFO     | budget:get_budget | sources per chunk = 5 (auto settings)
> 2021-07-08 15:57:33 | INFO     | budget:get_budget | rows per chunk    = 515 (auto settings)
> ```
> 
> Also, out of curiosity: that's 0.02 vs 0.1. But it seems to have reduced the chunk size by a factor of 5 in both the source and row dimension. Should that not decrease footprint by x25 then, in theory?

Yes, something is off then.

**Comment by paoloserra** [comment]
weird, we sorted this long ago and it had been behaving ever since... :(

**Comment by o-smirnov** [comment]
Here's a screenshot:

![image](https://user-images.githubusercontent.com/6470079/124935842-50812a80-e006-11eb-99b4-3bc3fb949642.png)

**Comment by sjperkins** [comment]
> 
> 
> weird, we sorted this long ago and it had been behaving ever since... :(

Yeah, @o-smirnov can you do a `pip freeze`  in the virtual env just for a sanity check?

**Comment by o-smirnov** [comment]
[pip-freeze.txt](https://github.com/paoloserra/crystalball/files/6785089/pip-freeze.txt)

I ran with ``-mf 0.01`` and watched htop carefully. It starts modest, but once the parallelism kicks in, RAM usage just grows at a steady 5GB/s, until it hits the buffers...

**Comment by o-smirnov** [comment]
For the record, trying it with https://github.com/ska-sa/dask-ms/tree/ignore-row-when-fixing-columns

The RAM growth is slower, and seems to go in spurts (climbs up by 20GB over a few seconds, then holds steady for another few). But it still won't survive until the end...

**Comment by o-smirnov** [comment]
No sorry forget I said https://github.com/paoloserra/crystalball/issues/45#issuecomment-876492603. The growth behaviour did not change with the updated dask-ms. It is a function of ``-mf`` it seems. Steady with ``-mf 0.01``, start-stop with ``-mf 0.1``.

**Comment by o-smirnov** [comment]
In a spirit of Trumpian doubling-down, I'm now running with ``-mf 0.5``. The start-stop growth definitely follows a trend: at -mf 0.5, the pattern is now grow by ~30-50GB, then hold steady and compute for a good long time. This repeats with every 8% increment of the progress bar. But! Overall the growth is slower (relative to progress percentage) with this higher -mf. Fingers crossed, if the trend holds, with ``-mf 0.5`` computation might actually finish **before** topping out the RAM!

**Comment by sjperkins** [comment]
@o-smirnov This is useful to know, I'm just going to finish off polishing up the SDSC and will give this a whirl locally. I feel like something may have changed upstream (perhaps in dask).

**Comment by o-smirnov** [comment]
This is more suspenseful than watching Italy play Spain. Will it live, will it die?

![image](https://user-images.githubusercontent.com/6470079/124943963-3bf46080-e00d-11eb-9eee-c8ef862ecd62.png)

**Comment by o-smirnov** [comment]
And as I type that, ~Morata misses his pen~ my RAM drops down to <130Gb at 80%! And then <80GB at 90%! And huzzah, my job finished! I'll leave it to you to puzzle out this behaviour. But at least I'm over the roadblock.

**Comment by IanHeywood** [comment]
I think you need more CPU cores.

**Comment by sjperkins** [comment]
> I think you need more CPU cores.

@o-smirnov Hire this man :-D

In other news, I can reproduce locally. Downgrading to dask==2021.1.1 fixes the problem, for the moment. So that will probably fix your current run, if not the soccer score.

**Comment by sjperkins** [comment]
Here's the issue.

https://github.com/dask/dask/issues/7583

dask==2021.3.1 is the last version without this problem.

**Comment by paoloserra** [comment]
I love waking up to a solved issue!

(and no, I haven't really just woken up)
