### ISSUE TITLE
add final self-congratulatory message

### ISSUE THREAD

**Issue by o-smirnov** [caracal-pipeline/crystalball#46]
The console log from a successful run currently looks like this:
```
# 2021-07-09 23:10:30 | INFO     | ms:ms_preprocess | inserting new column DIR1_DATA
# 2021-07-09 23:10:30 | INFO     | budget:get_budget | --------------------------------------------------
# 2021-07-09 23:10:30 | INFO     | budget:get_budget | Budgeting
# 2021-07-09 23:10:30 | INFO     | budget:get_budget | --------------------------------------------------
# 2021-07-09 23:10:30 | INFO     | budget:get_budget | system RAM = 503.37 GB
# 2021-07-09 23:10:30 | INFO     | budget:get_budget | nr of logical CPUs = 128
# 2021-07-09 23:10:30 | INFO     | budget:get_budget | nr sources = 224
# 2021-07-09 23:10:30 | INFO     | budget:get_budget | nr rows    = 931470
# 2021-07-09 23:10:30 | INFO     | budget:get_budget | nr chans   = 1024
# 2021-07-09 23:10:30 | INFO     | budget:get_budget | nr corrs   = 4
# 2021-07-09 23:10:30 | INFO     | budget:get_budget | sources per chunk = 103 (auto settings)
# 2021-07-09 23:10:30 | INFO     | budget:get_budget | rows per chunk    = 10308 (auto settings)
# 2021-07-09 23:10:30 | INFO     | budget:get_budget | expected memory usage = 50.33 GB
# 2021-07-09 23:10:30 | INFO     | crystalball:_predict | Field J2009-2026 DDID 0 rows 931470 chans 1024 corrs 4
# Successful read/write open of default-locked table ../msdir/1625623568_sdp_l0-J2009_2026-corr.ms: 27 columns, 931470 rows
# 
# [######################################### ] | 99% Complete (Estimate) |  2m 0s / ~ 2m 1s
```
The last line is a 99% progress bar, but the run seems successful.

It would be less confusing if it were to show 100%, and print a final "success" message.

**Comment by landmanbester** [comment]
Seconded. For me it ended with
```
(cball) bester@oates:~$ crystalball -sm PKS1934/
ApparentScale.Catalogs.PKSB1934-638.tar.gz  fitted.PKS1934.LBand.wsclean.cat.txt        fitted.PKS1934.UBand.wsclean.cat.txt
fitted.PKS1934.LBand.sdp.cat.txt            fitted.PKS1934.UBand.sdp.cat.txt
(cball) bester@oates:~$ crystalball -sm PKS1934/fitted.PKS1934.LBand.wsclean.cat.txt -o MODEL_DATA -j 32 -mf 0.25 projects/ESO137/msdir/ms1_primary.ms
2021-08-31 16:59:31 | INFO     | crystalball:_predict | Crystalball version 0.3.0
2021-08-31 16:59:31 | INFO     | wsclean:import_from_wsclean | PKS1934/fitted.PKS1934.LBand.wsclean.cat.txt contains 5153 components
2021-08-31 16:59:31 | INFO     | wsclean:import_from_wsclean | Total flux of 5153 selected components is 16.203687 Jy
Successful read/write open of default-locked table projects/ESO137/msdir/ms1_primary.ms: 30 columns, 708354 rows
2021-08-31 16:59:31 | INFO     | budget:get_budget | --------------------------------------------------
2021-08-31 16:59:31 | INFO     | budget:get_budget | Budgeting
2021-08-31 16:59:31 | INFO     | budget:get_budget | --------------------------------------------------
2021-08-31 16:59:31 | INFO     | budget:get_budget | system RAM = 503.56 GB
2021-08-31 16:59:31 | INFO     | budget:get_budget | nr of logical CPUs = 32
2021-08-31 16:59:31 | INFO     | budget:get_budget | nr sources = 5153
2021-08-31 16:59:31 | INFO     | budget:get_budget | nr rows    = 708354
2021-08-31 16:59:31 | INFO     | budget:get_budget | nr chans   = 4096
2021-08-31 16:59:31 | INFO     | budget:get_budget | nr corrs   = 4
2021-08-31 16:59:31 | INFO     | budget:get_budget | sources per chunk = 257 (auto settings)
2021-08-31 16:59:31 | INFO     | budget:get_budget | rows per chunk    = 25782 (auto settings)
2021-08-31 16:59:31 | INFO     | budget:get_budget | expected memory usage = 125.89 GB
2021-08-31 16:59:31 | INFO     | crystalball:_predict | Field J1939-6342 DDID 0 rows 708354 chans 4096 corrs 4
/home/bester/venvs/cball/lib/python3.7/site-packages/africanus/util/dask_util.py:122: FutureWarning: ignoring was deprecated in version 2021.06.1 and will be removed in a future release. Please use contextlib.suppress from the standard library instead.
  with ignoring(ValueError):
[ estimate improves over time              ] | 0% Complete (Estimate) |     1s / ~   23s/home/bester/venvs/cball/lib/python3.7/site-packages/africanus/util/dask_util.py:122: FutureWarning: ignoring was deprecated in version 2021.06.1 and will be removed in a future release. Please use contextlib.suppress from the standard library instead.
  with ignoring(ValueError):
/home/bester/venvs/cball/lib/python3.7/site-packages/africanus/util/dask_util.py:122: FutureWarning: ignoring was deprecated in version 2021.06.1 and will be removed in a future release. Please use contextlib.suppress from the standard library instead.
  with ignoring(ValueError):
[ estimate improves over time              ] | 0% Complete (Estimate) |     3s / ~    3s/home/bester/venvs/cball/lib/python3.7/site-packages/africanus/util/dask_util.py:122: FutureWarning: ignoring was deprecated in version 2021.06.1 and will be removed in a future release. Please use contextlib.suppress from the standard library instead.
  with ignoring(ValueError):
/home/bester/venvs/cball/lib/python3.7/site-packages/africanus/util/dask_util.py:122: FutureWarning: ignoring was deprecated in version 2021.06.1 and will be removed in a future release. Please use contextlib.suppress from the standard library instead.
  with ignoring(ValueError):
```
Not sure how serious these warnings are. Also, I'm pretty sure it was at a higher percentage at some point and it ran for at least a couple of hours. Now I am uncertain whether it ran through or not. I guess I'll check what MODEL_DATA looks like to find out

**Comment by sjperkins** [comment]
> 
> 
> Seconded. For me it ended with
> 
> ```
> (cball) bester@oates:~$ crystalball -sm PKS1934/
> ApparentScale.Catalogs.PKSB1934-638.tar.gz  fitted.PKS1934.LBand.wsclean.cat.txt        fitted.PKS1934.UBand.wsclean.cat.txt
> fitted.PKS1934.LBand.sdp.cat.txt            fitted.PKS1934.UBand.sdp.cat.txt
> (cball) bester@oates:~$ crystalball -sm PKS1934/fitted.PKS1934.LBand.wsclean.cat.txt -o MODEL_DATA -j 32 -mf 0.25 projects/ESO137/msdir/ms1_primary.ms
> 2021-08-31 16:59:31 | INFO     | crystalball:_predict | Crystalball version 0.3.0
> 2021-08-31 16:59:31 | INFO     | wsclean:import_from_wsclean | PKS1934/fitted.PKS1934.LBand.wsclean.cat.txt contains 5153 components
> 2021-08-31 16:59:31 | INFO     | wsclean:import_from_wsclean | Total flux of 5153 selected components is 16.203687 Jy
> Successful read/write open of default-locked table projects/ESO137/msdir/ms1_primary.ms: 30 columns, 708354 rows
> 2021-08-31 16:59:31 | INFO     | budget:get_budget | --------------------------------------------------
> 2021-08-31 16:59:31 | INFO     | budget:get_budget | Budgeting
> 2021-08-31 16:59:31 | INFO     | budget:get_budget | --------------------------------------------------
> 2021-08-31 16:59:31 | INFO     | budget:get_budget | system RAM = 503.56 GB
> 2021-08-31 16:59:31 | INFO     | budget:get_budget | nr of logical CPUs = 32
> 2021-08-31 16:59:31 | INFO     | budget:get_budget | nr sources = 5153
> 2021-08-31 16:59:31 | INFO     | budget:get_budget | nr rows    = 708354
> 2021-08-31 16:59:31 | INFO     | budget:get_budget | nr chans   = 4096
> 2021-08-31 16:59:31 | INFO     | budget:get_budget | nr corrs   = 4
> 2021-08-31 16:59:31 | INFO     | budget:get_budget | sources per chunk = 257 (auto settings)
> 2021-08-31 16:59:31 | INFO     | budget:get_budget | rows per chunk    = 25782 (auto settings)
> 2021-08-31 16:59:31 | INFO     | budget:get_budget | expected memory usage = 125.89 GB
> 2021-08-31 16:59:31 | INFO     | crystalball:_predict | Field J1939-6342 DDID 0 rows 708354 chans 4096 corrs 4
> /home/bester/venvs/cball/lib/python3.7/site-packages/africanus/util/dask_util.py:122: FutureWarning: ignoring was deprecated in version 2021.06.1 and will be removed in a future release. Please use contextlib.suppress from the standard library instead.
>   with ignoring(ValueError):
> [ estimate improves over time              ] | 0% Complete (Estimate) |     1s / ~   23s/home/bester/venvs/cball/lib/python3.7/site-packages/africanus/util/dask_util.py:122: FutureWarning: ignoring was deprecated in version 2021.06.1 and will be removed in a future release. Please use contextlib.suppress from the standard library instead.
>   with ignoring(ValueError):
> /home/bester/venvs/cball/lib/python3.7/site-packages/africanus/util/dask_util.py:122: FutureWarning: ignoring was deprecated in version 2021.06.1 and will be removed in a future release. Please use contextlib.suppress from the standard library instead.
>   with ignoring(ValueError):
> [ estimate improves over time              ] | 0% Complete (Estimate) |     3s / ~    3s/home/bester/venvs/cball/lib/python3.7/site-packages/africanus/util/dask_util.py:122: FutureWarning: ignoring was deprecated in version 2021.06.1 and will be removed in a future release. Please use contextlib.suppress from the standard library instead.
>   with ignoring(ValueError):
> /home/bester/venvs/cball/lib/python3.7/site-packages/africanus/util/dask_util.py:122: FutureWarning: ignoring was deprecated in version 2021.06.1 and will be removed in a future release. Please use contextlib.suppress from the standard library instead.
>   with ignoring(ValueError):
> ```
> 
> Not sure how serious these warnings are. Also, I'm pretty sure it was at a higher percentage at some point and it ran for at least a couple of hours. Now I am uncertain whether it ran through or not. I guess I'll check what MODEL_DATA looks like to find out

I doubt it's serious, -- it's saying that `dask.utils.ignoring` is deprecated, use contextlib.suppress instead

https://github.com/ska-sa/codex-africanus/blob/2f37e5c0d35adc627f1a9b83769b82083a167e80/africanus/util/dask_util.py#L11

Does it spam the console to the extent that it's impossible to tell what's going on?

**Comment by landmanbester** [comment]
Thanks @sjperkins, the MODEL_DATA column looks fully populated. That's the full output I pasted above so it's not too bad

**Comment by sjperkins** [comment]
Cool, it's an easy fix in codex https://github.com/ska-sa/codex-africanus/pull/256.

I think what I'm hearing is when will there be a new release and what do we want in it? I'll open a new issue about it.
